---
# Server setup on AWS

- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    region: ap-south-1
    ami: ami-c1503aae

  tasks:
    - name: Create security Group for the instance
      ec2_group:
        region: "{{ region }}"
        name: ckan_group
        description: SG for ckan docker containers
        rules:
          - proto: tcp
            ports:
              - 80
              - 22
              - 8080
              - 5000

            cidr_ip: 0.0.0.0/0
            rule_desc: Allow access to server
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      tags:
        - sg

    - name: Create EC2 Key Pair
      ec2_key:
        region: "{{ region }}"
        name: ckan_deploy
        state: present
      register: ckankey
    
    - name: Write the key to the file
      copy:
        content: "{{ ckankey.key.private_key }}"
        dest: "~/.ssh/ckankey.pem"
        mode: 600
      when: ckankey.changed

    
    - name: Provision EC2 Instance
      ec2:
        key_name: ckan_deploy
        region: "{{ region }}"
        instance_type: t2.medium
        group: ckan_group
        image: "{{ ami }}"
        wait: true
        user_data: "{{ lookup('file', 'user_data.sh') }}"
        exact_count: 1
        count_tag:
          Name: ckan-demo
        instance_tags:
          Name: ckan-demo
        volumes:
          - device_name: /dev/sda1
            device_type: gp2
            volume_size: 100
            delete_on_termination: true
      register: ec2
   
    - name: Associate New EIP
      ec2_eip:
        region: "{{ region }}"
        device_id: "{{ item }}"
      with_items: "{{ ec2.instance_ids }}"
      register: elastic_ip


    - name: Get the IP of the Instance
      ec2_instance_facts:
        filters:
          "tag:Name": ckan-demo
        region: "{{ region }}"
      register: ec2facts

    #   connection: local
    #   become: no
    #   lineinfile:
    #     path: "./hosts"
    #     regexp: "[aws1]"
    #     insertafter: "[aws1]"
    #     line: '{{ elastic_ip.public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/ckankey.pem'

